### ISSUE TITLE
Occasional Crash in pcache

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/service-manager#48]
Index out-of-range error when removing peer:
```
panic: runtime error: index out of range [2] with length 1

goroutine 142 [running]:
github.com/Multi-Tier-Cloud/service-manager/pcache.rpfs(...)
        /home/ubuntu/service-manager/pcache/pcache.go:90
github.com/Multi-Tier-Cloud/service-manager/pcache.(*PeerCache).updateCache(0x1b7fc80)
        /home/ubuntu/service-manager/pcache/pcache.go:169 +0x1852
github.com/Multi-Tier-Cloud/service-manager/pcache.(*PeerCache).UpdateCache(0x1b7fc80)
        /home/ubuntu/service-manager/pcache/pcache.go:250 +0xa7
created by main.main
        /home/ubuntu/service-manager/l4-proxy/l4-proxy.go:395 +0xc6d
```

Root cause seems to be due to modifying the slice while actively ranging over it. If removing a single element, it *usually* succeeds, but sometimes may trigger a crash (likely due to some underlying race condition).

The following code replicates this behaviour more reliably by trying to remove every other element:
```
package main

import (
	"fmt"
)

func rpfs(s []int, i uint) []int{
 	s[len(s)-1], s[i] = s[i], s[len(s)-1]
 	return s[:len(s)-1]
}

func main() {
	a := []int{0, 1, 2, 3, 4, 5, 6}
	
	for i := range a {
		if i % 2 == 1 {
			a = rpfs(a, uint(i))
		}
	}
	
	fmt.Printf("slice is: %#v\n", a)
	return
}
```

**Comment by hivanco** [comment]
Was looking at the pcache an noticed a case where rpfs() wasn't being used properly. Haven't tested if my theory is correct but I'm pretty sure its a possible error case nonetheless.

Some background: The rpfs() function relies on the fact that after using it, you need to decrement the index variable so that on the next iteration, you don't miss an element. It swaps the last element with the current element that is to be deleted, and shrinks the slice by 1. So after rpfs(), the new current element has not been visited yet. Without decrementing the index, the next iteration will erroneously move onto the next element, skipping the new current element.

A key caveat is this means you can only use rpfs() with the 3-component initialize/condition/update style for loops, in order to decrement the index variable, and so if the length decreases, the condition will see that.

This is how its supposed to be used:
https://github.com/Multi-Tier-Cloud/service-manager/blob/7e6c5aecddb29c1f3f9a8ce005c4d25c822edfaf/pcache/pcache.go#L194-L196

Where the error happens, looks like the index does not get decremented, and its using a range based for loop:
https://github.com/Multi-Tier-Cloud/service-manager/blob/7e6c5aecddb29c1f3f9a8ce005c4d25c822edfaf/pcache/pcache.go#L169

In this context, if you delete the 2nd last element in a slice, you will try to visit the next element on the next iteration, causing an index-out-of-range error.
Eg. If you start with a slice with 2 elements: ["A", "B"], and you want to delete "A".
i = 0, delete "A", slice now looks like ["B"]
i = 1, index-out-range
This example seems to match the error message.

**Comment by hivanco** [comment]
On a somewhat related note, didn't use this, but probably a good idea to try it out on any concurrent code. Apparently Golang provides a data race detector tool:
https://golang.org/doc/articles/race_detector.html

**Comment by hivanco** [comment]
Might want to consider using a slice of maps instead of a slice of slices for pcache. This eliminates the burden of deleting an element from the middle of a slice. Deleting from a map is an O(1) operation. Would also speed up searching for a peer, also an O(1) operation in a map, compared to O(n) in a slice.

**Comment by t-lin** [comment]
Thanks for the fix! I'll see if I encounter this issue anymore (it was pretty sporadic in the first place) and report back here if I see it again.

> Would also speed up searching for a peer, also an O(1) operation in a map, compared to O(n) in a slice.

**Warning**: I'm about to get nit-picky

It depends on how large _n_ is. For smaller _n_'s, it's likely that the operations in a map (i.e. hash lookup to resolve item to a pointer addresses, then do a fetch from main memory) takes longer than simply fetching an entire cache line of data from memory and iterating through it. The question is where that cut-off pointer is (which varies depending on CPU, RAM, etc.).

Some talks about this topic if you're interested in digging further:
https://www.youtube.com/watch?v=jEG4Qyo_4Bc (slices vs maps in golang)
https://www.youtube.com/watch?v=DyG9S9nAlUM (arrays vs linked lists in C and assembly; not quite the same as maps, but maps turn to linked lists when items hash to the same bin.)
